version: '3'

services:
  nginx:
    container_name: nginx
    build: requirements/nginx
    hostname: localhost
    volumes:
      - wp:/var/www/wordpress
    networks:
      - project
    ports:
      - "443:443"
    depends_on:
      - wordpress
    restart: always
  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    hostname: localhost
    volumes:
      - db:/var/lib/mysql
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PARRWORD}
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    networks:
      - project
    restart: always
  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    hostname: localhost
    volumes:
      - wp:/var/www/wordpress
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      USER_NAME: ${USER_NAME}
      USER_EMAIL: ${USER_EMAIL}
      USER_ADMIN_EMAIL: ${USER_ADMIN_EMAIL}
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      DOMAIN_NAME: ${DOMAIN_NAME}
      TITLE: ${TITLE}
    networks:
      - project
    depends_on:
      - mariadb
    restart: always

volumes:
  db:
    driver: local
    driver_opts:
      typr: none
      o: bind
      device: ~/data/db
  wp:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/data/wp
networks:
  project:
    driver: bridge